name: Daily Policy Data Commit

on:
  # Schedule the job to run daily at 12:00 PM UTC
  schedule:
    - cron: '0 12 * * *' 
  # Allows you to run this workflow manually from the Actions tab in GitHub
  workflow_dispatch:

jobs:
  publish_policies:
    # Use a fresh, standard Ubuntu environment
    runs-on: ubuntu-latest
    
    # Grant permissions for the job to write back to the repository
    permissions:
      contents: write
      
    steps:
      - name: Checkout Repository
        # Action to pull down your code
        uses: actions/checkout@v4

      - name: Set up Python Environment
        # Action to install Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        # Install all packages listed in your requirements.txt file
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Policy Scraper and Commit Data File
        # This executes your main Python script.
        # It securely reads the REPO_ACCESS_TOKEN to get commit permissions.
        env:
          REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          echo "Starting daily policy update run..."
          python publish_daily_updates.py
          echo "Policy update job finished."
```

---

## Critical Next Steps

For this YAML file to work, you **must** ensure your Python script and requirements file are also updated to remove the old Firebase logic.

### 1. `requirements.txt` (Must be updated)
This file must be simplified to this:
```
requests
beautifulsoup4

